-- 8. Watchlist cleanup (2026-10-02)
-- a) Renamed / replaced tickers that no longer quote
UPDATE watchlist SET ticker = 'P', name = 'Everpure, Inc. (formerly Pure Storage)' WHERE ticker = 'PSTG';
UPDATE watchlist SET ticker = 'KEEL', name = 'Keel Infrastructure Corp. (formerly Bitfarms)' WHERE ticker = 'BITF';
UPDATE watchlist SET ticker = 'QBTS', name = 'D-Wave Quantum Inc.' WHERE ticker = 'D-WAVE';
UPDATE watchlist SET ticker = 'DRNZ', name = 'REX Drone ETF' WHERE ticker = 'UAV';

-- b) Consolidate categories to '<Main group> / <Sub-category>'
UPDATE watchlist SET category = 'Clean Energy & Storage / Clean Energy Finance' WHERE category = 'Clean Energy Finance';
UPDATE watchlist SET category = 'Clean Energy & Storage / Energy Storage' WHERE category = 'Energy Storage';
UPDATE watchlist SET category = 'Clean Energy & Storage / Hydro' WHERE category = 'Clean Power / Hydro';
UPDATE watchlist SET category = 'Clean Energy & Storage / Power & Energy Storage' WHERE category = 'Power & Energy Storage';
UPDATE watchlist SET category = 'Clean Energy & Storage / Renewables' WHERE category = 'Clean Power / Renewables';
UPDATE watchlist SET category = 'Clean Energy & Storage / Software' WHERE category = 'Energy Storage / Software';
UPDATE watchlist SET category = 'Clean Energy & Storage / Solar & Energy Storage' WHERE category = 'Solar & Energy Storage';
UPDATE watchlist SET category = 'Clean Energy & Storage / Solar & Inverters' WHERE category = 'Solar & Inverters';
UPDATE watchlist SET category = 'Clean Energy & Storage / Solar & Storage' WHERE category = 'Solar & Storage';
UPDATE watchlist SET category = 'Clean Energy & Storage / Solar Technology' WHERE category = 'Solar Technology';
UPDATE watchlist SET category = 'Cloud & Software / AI' WHERE category = 'Creative Software / AI';
UPDATE watchlist SET category = 'Cloud & Software / Cloud & AI Research' WHERE category = 'Cloud & AI Research';
UPDATE watchlist SET category = 'Cloud & Software / Cloud & Enterprise Software' WHERE category = 'Cloud & Enterprise Software';
UPDATE watchlist SET category = 'Cloud & Software / Cloud Data Infrastructure' WHERE category = 'Cloud Data Infrastructure';
UPDATE watchlist SET category = 'Cloud & Software / Cloud Infrastructure' WHERE category = 'Cloud Infrastructure';
UPDATE watchlist SET category = 'Cloud & Software / Database Infrastructure' WHERE category = 'Cloud / Database Infrastructure';
UPDATE watchlist SET category = 'Cloud & Software / Defense' WHERE category = 'Enterprise AI / Defense';
UPDATE watchlist SET category = 'Cloud & Software / Edge AI' WHERE category = 'Consumer Tech / Edge AI';
UPDATE watchlist SET category = 'Cloud & Software / Enterprise AI' WHERE category = 'Software / Enterprise AI';
UPDATE watchlist SET category = 'Cloud & Software / Enterprise Software' WHERE category = 'Enterprise Software';
UPDATE watchlist SET category = 'Crypto & HPC Compute / Compute' WHERE category = 'Crypto / Compute';
UPDATE watchlist SET category = 'Crypto & HPC Compute / Data Centers' WHERE category = 'Crypto / Data Centers';
UPDATE watchlist SET category = 'Crypto & HPC Compute / HPC AI Cloud' WHERE category = 'Crypto / HPC AI Cloud';
UPDATE watchlist SET category = 'Crypto & HPC Compute / HPC AI Hosting' WHERE category = 'Crypto / HPC AI Hosting';
UPDATE watchlist SET category = 'Crypto & HPC Compute / Infrastructure' WHERE category = 'Crypto / Infrastructure';
UPDATE watchlist SET category = 'Crypto & HPC Compute / Zero-Carbon Compute' WHERE category = 'Crypto / Zero-Carbon Compute';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / AI Infrastructure' WHERE category = 'Tech / AI Infrastructure';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / AI Racks' WHERE category = 'Hardware / AI Racks';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / AI Servers' WHERE category = 'Hardware / AI Servers';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / Data Center Infrastructure' WHERE category = 'Data Center Infrastructure';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / Data Storage' WHERE category = 'Data Storage';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / Grid' WHERE category = 'Data Center Cooling / Grid';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / Supercomputing' WHERE category = 'Hardware / Supercomputing';
UPDATE watchlist SET category = 'Data Centers & AI Hardware / Thermal Management' WHERE category = 'Thermal Management';
UPDATE watchlist SET category = 'Defense & Aerospace / Aerospace' WHERE category = 'Defense / Aerospace';
UPDATE watchlist SET category = 'Defense & Aerospace / Autonomous Aerial' WHERE category = 'Aerospace / Autonomous Aerial';
UPDATE watchlist SET category = 'Defense & Aerospace / Autonomous Drones' WHERE category = 'Defense / Autonomous Drones';
UPDATE watchlist SET category = 'Defense & Aerospace / Defense' WHERE category = 'Aerospace / Defense';
UPDATE watchlist SET category = 'Defense & Aerospace / Defense Components' WHERE category = 'Aerospace / Defense Components';
UPDATE watchlist SET category = 'Defense & Aerospace / Defense Prime' WHERE category = 'Defense Prime';
UPDATE watchlist SET category = 'Defense & Aerospace / Drones' WHERE category = 'Defense / Drones';
UPDATE watchlist SET category = 'Defense & Aerospace / Electronic Warfare' WHERE category = 'Defense / Electronic Warfare';
UPDATE watchlist SET category = 'Defense & Aerospace / IT Solutions' WHERE category = 'Defense / IT Solutions';
UPDATE watchlist SET category = 'Defense & Aerospace / Intelligence Consulting' WHERE category = 'Defense / Intelligence Consulting';
UPDATE watchlist SET category = 'Defense & Aerospace / Law Enforcement Tech' WHERE category = 'Defense / Law Enforcement Tech';
UPDATE watchlist SET category = 'Defense & Aerospace / Micro-Gimbals' WHERE category = 'Defense / Micro-Gimbals';
UPDATE watchlist SET category = 'Defense & Aerospace / Naval' WHERE category = 'Defense / Naval';
UPDATE watchlist SET category = 'Defense & Aerospace / Proprietary Parts' WHERE category = 'Aerospace / Proprietary Parts';
UPDATE watchlist SET category = 'Defense & Aerospace / UAS & Avionics' WHERE category = 'Defense / UAS & Avionics';
UPDATE watchlist SET category = 'Defense & Aerospace / eVTOL' WHERE category = 'Aerospace / eVTOL';
UPDATE watchlist SET category = 'Energy / Energy Infrastructure' WHERE category = 'Energy Infrastructure';
UPDATE watchlist SET category = 'Grid & Electrical / E-Infrastructure Construction' WHERE category = 'E-Infrastructure Construction';
UPDATE watchlist SET category = 'Grid & Electrical / Electrical Contracting' WHERE category = 'Electrical Contracting';
UPDATE watchlist SET category = 'Grid & Electrical / Electrical Equipment' WHERE category = 'Electrical Equipment';
UPDATE watchlist SET category = 'Grid & Electrical / Fuel Cells' WHERE category = 'Grid Tech / Fuel Cells';
UPDATE watchlist SET category = 'Grid & Electrical / Grid Contracting' WHERE category = 'Grid Contracting';
UPDATE watchlist SET category = 'Grid & Electrical / Grid Infrastructure Services' WHERE category = 'Grid Infrastructure Services';
UPDATE watchlist SET category = 'Grid & Electrical / Infrastructure Engineering' WHERE category = 'Infrastructure Engineering';
UPDATE watchlist SET category = 'Grid & Electrical / Power Distribution' WHERE category = 'Power Distribution';
UPDATE watchlist SET category = 'Grid & Electrical / Power Management' WHERE category = 'Power Management';
UPDATE watchlist SET category = 'Grid & Electrical / Superconductors' WHERE category = 'Grid Tech / Superconductors';
UPDATE watchlist SET category = 'Industrials & HVAC / Building Systems' WHERE category = 'HVAC / Building Systems';
UPDATE watchlist SET category = 'Industrials & HVAC / Climate Innovation' WHERE category = 'HVAC / Climate Innovation';
UPDATE watchlist SET category = 'Industrials & HVAC / HVAC' WHERE category = 'Industrial / HVAC';
UPDATE watchlist SET category = 'Industrials & HVAC / HVAC & Mechanical' WHERE category = 'HVAC & Mechanical';
UPDATE watchlist SET category = 'Industrials & HVAC / Industrial Cooling' WHERE category = 'HVAC / Industrial Cooling';
UPDATE watchlist SET category = 'Industrials & HVAC / Industrial Distribution' WHERE category = 'Industrial Distribution';
UPDATE watchlist SET category = 'Industrials & HVAC / Industrial Engineering' WHERE category = 'Industrial Engineering';
UPDATE watchlist SET category = 'Mining & Materials / Copper' WHERE category = 'Mining / Copper';
UPDATE watchlist SET category = 'Mining & Materials / Copper & Zinc' WHERE category = 'Mining / Copper & Zinc';
UPDATE watchlist SET category = 'Mining & Materials / Diversified' WHERE category = 'Mining / Diversified';
UPDATE watchlist SET category = 'Mining & Materials / Iron Ore & Nickel' WHERE category = 'Mining / Iron Ore & Nickel';
UPDATE watchlist SET category = 'Mining & Materials / Lithium' WHERE category = 'Critical Materials / Lithium';
UPDATE watchlist SET category = 'Mining & Materials / Rare Earths' WHERE category = 'Critical Materials / Rare Earths';
UPDATE watchlist SET category = 'Networking & Electronics / Cloud' WHERE category = 'Networking / Cloud';
UPDATE watchlist SET category = 'Networking & Electronics / Cloud-Managed' WHERE category = 'Networking / Cloud-Managed';
UPDATE watchlist SET category = 'Networking & Electronics / Enterprise' WHERE category = 'Networking / Enterprise';
UPDATE watchlist SET category = 'Networking & Electronics / Test & Measurement' WHERE category = 'Electronics / Test & Measurement';
UPDATE watchlist SET category = 'Nuclear / Engineering' WHERE category = 'Engineering / Nuclear';
UPDATE watchlist SET category = 'Nuclear / Nuclear & Rare Earths' WHERE category = 'Nuclear & Rare Earths';
UPDATE watchlist SET category = 'Nuclear / Nuclear Components & Defense' WHERE category = 'Nuclear Components & Defense';
UPDATE watchlist SET category = 'Nuclear / Nuclear Energy' WHERE category = 'Nuclear Energy';
UPDATE watchlist SET category = 'Photonics / Interconnects & Optical' WHERE category = 'Interconnects & Optical';
UPDATE watchlist SET category = 'Quantum Computing / Enterprise Tech & Quantum' WHERE category = 'Enterprise Tech & Quantum';
UPDATE watchlist SET category = 'Quantum Computing / Photonics' WHERE category = 'Quantum / Photonics';
UPDATE watchlist SET category = 'Semiconductors / Power Semiconductors' WHERE category = 'Power Semiconductors';
UPDATE watchlist SET category = 'Semiconductors / Semiconductor Equipment' WHERE category = 'Semiconductor Equipment';
UPDATE watchlist SET category = 'Space / Satellite Communications' WHERE category = 'Satellite Communications';
UPDATE watchlist SET category = 'Utilities & Power / Nuclear' WHERE category = 'Utilities / Nuclear';
UPDATE watchlist SET category = 'Utilities & Power / Nuclear & Gas' WHERE category = 'Power / Nuclear & Gas';
UPDATE watchlist SET category = 'Utilities & Power / Nuclear Baseload' WHERE category = 'Power / Nuclear Baseload';
UPDATE watchlist SET category = 'Utilities & Power / Regulated Power' WHERE category = 'Utilities / Regulated Power';
UPDATE watchlist SET category = 'Utilities & Power / Transmission' WHERE category = 'Utilities / Transmission';
UPDATE watchlist SET category = 'Water / Water & Gas Utilities' WHERE category = 'Water & Gas Utilities';
UPDATE watchlist SET category = 'Water / Water Management' WHERE category = 'Water Management';
UPDATE watchlist SET category = 'Water / Water Technology' WHERE category = 'Water Technology';
UPDATE watchlist SET category = 'Water / Water Utilities' WHERE category = 'Water Utilities';
