[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#141413"
secondaryBackgroundColor = "#1f1f1d"
textColor = "#f2f1ec"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
